# Generated by Django 3.1.7 on 2021-05-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/05:02:57/y/c0/36918169-60e9-444c-b118-4d150ada3ac8/'),
        ),
    ]
