# Generated by Django 3.1.7 on 2021-05-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0002_auto_20210502_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/05:30:13/y/c0/87773f58-7e35-493e-b4dd-ac87d87fb80e/'),
        ),
    ]
