# Generated by Django 3.1.7 on 2021-05-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0003_auto_20210502_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/21:53:47/y/c0/00ce3b8e-9ab3-4999-b95e-ac54ba70f4da/'),
        ),
    ]
