# Generated by Django 3.1.7 on 2021-06-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0004_auto_20210502_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/01:03:22/y/c0/9453843e-d3f6-459a-a868-fc06628a625a/'),
        ),
    ]
