# Generated by Django 3.1.7 on 2021-06-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0005_auto_20210616_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/03:36:30/y/c0/3addb757-c531-4b29-ac38-5727b107e1a5/'),
        ),
    ]
