# Generated by Django 3.1.7 on 2021-06-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0006_auto_20210616_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/04:07:02/y/c0/462b59bd-c31d-4699-b7e2-f41bfe0e2a8f/'),
        ),
    ]
