# Generated by Django 3.1.7 on 2021-06-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0007_auto_20210616_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/21:45:31/y/c0/97ab915f-e515-4a33-8f41-d6585e299797/'),
        ),
    ]
