# Generated by Django 3.1.7 on 2021-06-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0008_auto_20210621_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/22:28:16/y/c0/4d9908fe-a8e9-485b-98ab-59059a3a7b78/'),
        ),
    ]
