# Generated by Django 3.1.7 on 2021-06-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0009_auto_20210623_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/22:53:45/y/c0/99cb06d9-9681-43d5-9144-a86dab33b766/'),
        ),
    ]
