# Generated by Django 3.1.7 on 2021-06-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0010_auto_20210623_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/23:15:11/y/c0/757872fb-161c-4ce8-9b51-1ff9ca2827ef/'),
        ),
    ]
