# Generated by Django 3.1.7 on 2021-06-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0011_auto_20210623_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/23:44:53/y/c0/733fc56a-a42b-47a1-864f-925abbf90856/'),
        ),
    ]
