# Generated by Django 3.1.7 on 2021-06-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0012_auto_20210623_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/01:18:01/y/c0/ac2ac4b6-f85b-401b-a948-b2443e187b5c/'),
        ),
    ]
