# Generated by Django 3.1.7 on 2021-06-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile0', '0013_auto_20210624_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image_pic',
            field=models.ImageField(upload_to='users/01:21:04/y/c0/4065994e-54a2-48d9-80e9-b3dbf9d5b7e4/'),
        ),
    ]
