# Generated by Django 3.1.7 on 2021-04-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userpr/5c738497-0580-40ce-a73c-a2abe73a202d/uploads'),
        ),
    ]
