# Generated by Django 3.1.7 on 2021-05-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210429_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userpr/5dc9cc90-91fa-4d3d-9156-b0041b74a5ff/uploads'),
        ),
    ]
