# Generated by Django 3.1.7 on 2021-05-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210502_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userpr/d745ad89-3e7c-4bc9-a8f6-74595c254f6c/uploads'),
        ),
    ]
