# Generated by Django 3.1.7 on 2021-05-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210502_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userpr/71fcfda1-c0b9-4e39-9752-beead3129678/uploads'),
        ),
    ]
