# Generated by Django 3.1.7 on 2021-06-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210616_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userpr/085c4779-da5a-4d5f-b6a1-a05de2f41a7e/uploads'),
        ),
    ]
