# Generated by Django 3.1.7 on 2021-06-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210623_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userpr/4e50fc2c-a8b1-4809-9fa6-f6568ef34d6c/uploads'),
        ),
    ]
