# Generated by Django 3.1.7 on 2021-06-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210623_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userpr/7188c08c-d1c4-441e-b906-4fec5ea81771/uploads'),
        ),
    ]
