# Generated by Django 3.1.7 on 2021-05-03 01:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None)),
                ('postimg', models.ImageField(upload_to='posts/P/p')),
                ('postfile', models.ImageField(upload_to='posts/2021-05-03/doct/P/v/')),
                ('posttitle', models.CharField(default='', max_length=30)),
                ('potBody', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentbody', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('commenttag', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('commentdate', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='Product description.')),
                ('file_comment', models.FileField(upload_to='comments/2021-05-03/docs/P')),
                ('image_url', models.ImageField(upload_to='comments/2021-05-03/c0/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.posts')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
