# Generated by Django 3.1.7 on 2021-05-03 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='file_comment',
            field=models.FileField(upload_to='comments/2021-05-03/docs/Z'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postfile',
            field=models.ImageField(upload_to='posts/2021-05-03/doct/Z/v/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postimg',
            field=models.ImageField(upload_to='posts/Z/p'),
        ),
    ]
