# Generated by Django 3.1.7 on 2021-06-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210503_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='file_comment',
            field=models.FileField(upload_to='comments/2021-06-16/docs/Y'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='image_url',
            field=models.ImageField(upload_to='comments/2021-06-16/c0/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postfile',
            field=models.ImageField(upload_to='posts/2021-06-16/doct/Y/v/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postimg',
            field=models.ImageField(upload_to='posts/Y/p'),
        ),
    ]
