# Generated by Django 3.1.7 on 2021-06-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20210623_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='file_comment',
            field=models.FileField(upload_to='comments/2021-06-24/docs/c'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='image_url',
            field=models.ImageField(upload_to='comments/2021-06-24/c0/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postfile',
            field=models.ImageField(upload_to='posts/2021-06-24/doct/c/v/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postimg',
            field=models.ImageField(upload_to='posts/c/p'),
        ),
    ]
