# Generated by Django 3.1.7 on 2021-06-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20210616_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='images/<property object at 0x03F48E10>'),
        ),
        migrations.AlterField(
            model_name='poststory',
            name='image',
            field=models.FileField(blank=True, upload_to='storyies/<property object at 0x03F48E10>/<built-in method now of type object at 0x69DBC3B0>/0'),
        ),
    ]
