# Generated by Django 3.1.7 on 2021-06-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_auto_20210624_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='images/<property object at 0x043A9A00>'),
        ),
        migrations.AlterField(
            model_name='poststory',
            name='image',
            field=models.FileField(blank=True, upload_to='storyies/<property object at 0x043A9A00>/<built-in method now of type object at 0x69DBC3B0>/0'),
        ),
    ]
