# Generated by Django 3.1.7 on 2021-04-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('prod_img', models.ImageField(upload_to='products/')),
                ('quantity', models.IntegerField(default=20)),
                ('remise_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('description', models.TextField()),
                ('rate', models.IntegerField()),
                ('document', models.FileField(upload_to='generaldesc/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
