# Generated by Django 3.1.7 on 2021-05-05 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=112)),
                ('content', models.TextField()),
                ('p_date', models.DateTimeField(editable=False, null=True)),
                ('u_date', models.DateTimeField(null=True)),
                ('image_feed', models.ImageField(blank=True, upload_to='feed/images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedlikes', to='feed.feed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedlikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('p_date', models.DateTimeField(editable=False, null=True)),
                ('u_date', models.DateTimeField(null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedcomments', to='feed.feed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedcomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
