# Generated by Django 3.1.7 on 2021-05-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepe', '0003_auto_20210502_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='reciepe/W/'),
        ),
    ]
