# Generated by Django 3.1.7 on 2021-06-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepe', '0008_auto_20210616_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='reciepe/K/'),
        ),
    ]
