# Generated by Django 3.1.7 on 2021-06-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='food/92/2021-06-21 08:22:01.848336/<django.db.models.fields.CharField>')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='foodposts/2021-06-21 08:22:01.849089/images/24')),
                ('foodpost', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='foodpost', to='myfood.foodpost')),
            ],
        ),
    ]
