# Generated by Django 3.1.7 on 2021-06-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfood', '0008_auto_20210624_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='image',
            field=models.FileField(blank=True, upload_to='food/54/2021'),
        ),
        migrations.AlterField(
            model_name='foodpostimage',
            name='images',
            field=models.FileField(upload_to='foodposts/2021/images/5'),
        ),
    ]
