# Generated by Django 3.1.7 on 2021-06-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipevideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipevideo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='reciepevideos/R/'),
        ),
        migrations.AlterField(
            model_name='recipevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recipesvideosusers/R/'),
        ),
    ]
