# Generated by Django 3.1.7 on 2021-06-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipevideo', '0005_auto_20210616_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipevideo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='reciepevideos/j/'),
        ),
        migrations.AlterField(
            model_name='recipevideo',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='rvideos/j/videorecipes'),
        ),
        migrations.AlterField(
            model_name='recipevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recipesvideosusers/j/'),
        ),
    ]
