# Generated by Django 3.1.7 on 2021-06-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipevideo', '0010_auto_20210623_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipevideo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='reciepevideos/V/'),
        ),
        migrations.AlterField(
            model_name='recipevideo',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='rvideos/V/videorecipes'),
        ),
        migrations.AlterField(
            model_name='recipevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recipesvideosusers/V/'),
        ),
    ]
